security:
    encoders:
        App\Entity\Student:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\Student
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
