sonata_admin:
  templates:
    layout: "@SonataAdmin/standard_layout.html.twig"
    ajax: "@SonataAdmin/ajax_layout.html.twig"
    show: "@SonataAdmin/CRUD/show.html.twig"
    edit: "@SonataAdmin/CRUD/edit.html.twig"
    list: "@SonataAdmin/CRUD/list.html.twig"
    action: "@SonataAdmin/CRUD/action.html.twig"
    select: "@SonataAdmin/CRUD/list__select.html.twig"
    list_block: "@SonataAdmin/Block/block_admin_list.html.twig"
    short_object_description: "@SonataAdmin/Helper/short-object-description.html.twig"
    batch: "@SonataAdmin/CRUD/list__batch.html.twig"
    inner_list_row: "@SonataAdmin/CRUD/list_inner_row.html.twig"
    base_list_field: "@SonataAdmin/CRUD/base_list_field.html.twig"
    pager_links: "@SonataAdmin/Pager/links.html.twig"
    pager_results: "@SonataAdmin/Pager/results.html.twig"
  assets:
    extra_javascripts:
      - bundles/sonatapage/sonata-page.back.min.js
    extra_stylesheets:
      - bundles/sonatapage/sonata-page.back.min.css

sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]
sonata_doctrine_orm_admin:
  # default value is null, so doctrine uses the value defined in the configuration
  entity_manager: ~

  audit:
    force: true

  templates:
    form:
      - "@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig"
    filter:
      - "@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig"
    types:
      list:
        array: "@SonataAdmin/CRUD/list_array.html.twig"
        boolean: "@SonataAdmin/CRUD/list_boolean.html.twig"
        date: "@SonataAdmin/CRUD/list_date.html.twig"
        time: "@SonataAdmin/CRUD/list_time.html.twig"
        datetime: "@SonataAdmin/CRUD/list_datetime.html.twig"
        text: "@SonataAdmin/CRUD/base_list_field.html.twig"
        trans: "@SonataAdmin/CRUD/list_trans.html.twig"
        string: "@SonataAdmin/CRUD/base_list_field.html.twig"
        smallint: "@SonataAdmin/CRUD/base_list_field.html.twig"
        bigint: "@SonataAdmin/CRUD/base_list_field.html.twig"
        integer: "@SonataAdmin/CRUD/base_list_field.html.twig"
        decimal: "@SonataAdmin/CRUD/base_list_field.html.twig"
        identifier: "@SonataAdmin/CRUD/base_list_field.html.twig"
        currency: "@SonataAdmin/CRUD/list_currency.html.twig"
        percent: "@SonataAdmin/CRUD/list_percent.html.twig"
        choice: "@SonataAdmin/CRUD/list_choice.html.twig"
        url: "@SonataAdmin/CRUD/list_url.html.twig"

      show:
        array: "@SonataAdmin/CRUD/show_array.html.twig"
        boolean: "@SonataAdmin/CRUD/show_boolean.html.twig"
        date: "@SonataAdmin/CRUD/show_date.html.twig"
        time: "@SonataAdmin/CRUD/show_time.html.twig"
        datetime: "@SonataAdmin/CRUD/show_datetime.html.twig"
        text: "@SonataAdmin/CRUD/base_show_field.html.twig"
        trans: "@SonataAdmin/CRUD/show_trans.html.twig"
        string: "@SonataAdmin/CRUD/base_show_field.html.twig"
        smallint: "@SonataAdmin/CRUD/base_show_field.html.twig"
        bigint: "@SonataAdmin/CRUD/base_show_field.html.twig"
        integer: "@SonataAdmin/CRUD/base_show_field.html.twig"
        decimal: "@SonataAdmin/CRUD/base_show_field.html.twig"
        currency: "@SonataAdmin/CRUD/base_currency.html.twig"
        percent: "@SonataAdmin/CRUD/base_percent.html.twig"
        choice: "@SonataAdmin/CRUD/show_choice.html.twig"
        url: "@SonataAdmin/CRUD/show_url.html.twig"
