#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
  prefix: /{user}
  type: annotation
  resource: App\Controller\AdminController

Page:
  path: /{user}/{pages}
  controller: App\Controller\AdminController::Student
