<?php

namespace ContainerO51M8PF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VFNKYZ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VFNKYZ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VFNKYZ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'args' => ['privates', '.errored..service_locator.VFNKYZ1.Doctrine\\ORM\\Event\\LifecycleEventArgs', NULL, 'Cannot autowire service ".service_locator.VFNKYZ1": it references class "Doctrine\\ORM\\Event\\LifecycleEventArgs" but no such service exists.'],
        ], [
            'args' => 'Doctrine\\ORM\\Event\\LifecycleEventArgs',
        ]);
    }
}
