<?php

namespace ContainerO51M8PF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdmin_Course_TemplateRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'admin.course.template_registry' shared service.
     *
     * @return \Sonata\AdminBundle\Templating\TemplateRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['admin.course.template_registry'] = new \Sonata\AdminBundle\Templating\TemplateRegistry($container->parameters['sonata.admin.configuration.templates']);
    }
}
