<?php

namespace ContainerO51M8PF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLifecycleEventArgsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VFNKYZ1.Doctrine\ORM\Event\LifecycleEventArgs' shared service.
     *
     * @return \Doctrine\ORM\Event\LifecycleEventArgs
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VFNKYZ1": it references class "Doctrine\\ORM\\Event\\LifecycleEventArgs" but no such service exists.');
    }
}
