<?php

namespace ContainerO51M8PF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StudentsController' shared autowired service.
     *
     * @return \App\Controller\StudentsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'StudentsController.php';

        $container->services['App\\Controller\\StudentsController'] = $instance = new \App\Controller\StudentsController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->get_ServiceLocator_5nX7ca3Service())->withContext('App\\Controller\\StudentsController', $container));

        return $instance;
    }
}
