<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO51M8PF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO51M8PF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO51M8PF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO51M8PF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO51M8PF\App_KernelDevDebugContainer([
    'container.build_hash' => 'O51M8PF',
    'container.build_id' => 'e4a2148a',
    'container.build_time' => 1610733070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO51M8PF');
